#!/bin/sh
cd ${0%/*} || exit 1    # Run from this directory

# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions

runApplication decomposePar
echo Running $(getApplication) on $(pwd)
mpiexec -np 30 $(getApplication) -parallel > log.$(getApplication)

echo Run complete.

#------------------------------------------------------------------------------
